# Generated by Django 4.2.16 on 2025-05-15 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('FREAD', '프리드 분석'), ('IMPROVMENT', '문장 개선')], max_length=20, verbose_name='분석 카테고리')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='분석 제목')),
                ('original_text', models.TextField(verbose_name='원본 텍스트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='분석 생성 일시')),
            ],
            options={
                'verbose_name': '분석 요청',
                'verbose_name_plural': '분석 요청 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreadAnalysis',
            fields=[
                ('analysis_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analysis_result', serialize=False, to='analyses.analysis', verbose_name='연결된 통합 분석')),
                ('total', models.FloatField(verbose_name='완성도')),
                ('logic', models.IntegerField(verbose_name='설득력 점수')),
                ('appeal', models.IntegerField(verbose_name='전달력 점수')),
                ('focus', models.IntegerField(verbose_name='몰입도 점수')),
                ('simplicity', models.IntegerField(verbose_name='문장 간결성 점수')),
                ('popularity', models.IntegerField(verbose_name='대중성 점수')),
                ('ai_comments_data', models.JSONField(verbose_name='예상 댓글 데이터 (JSON)')),
                ('solutions_data', models.JSONField(verbose_name='솔루션 제안 데이터 (JSON)')),
            ],
            options={
                'verbose_name': 'Fread 분석 결과',
                'verbose_name_plural': 'Fread 분석 결과 목록',
            },
        ),
    ]
