# Generated by Django 5.1.4 on 2025-05-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freadanalysis",
            name="original_text",
            field=models.TextField(default="", verbose_name="원본 텍스트"),
            preserve_default=False,
        ),
    ]
