# Generated by Django 4.2.16 on 2025-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('organizer', models.CharField(max_length=100, verbose_name='주최사')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='마감일')),
                ('target_audience', models.TextField(verbose_name='참여 대상')),
                ('has_prize', models.BooleanField(default=False, verbose_name='상금 제공 유무')),
                ('prize_details', models.TextField(blank=True, verbose_name='상금 정보')),
                ('details_url', models.URLField(blank=True, verbose_name='상세 정보 URL')),
                ('image', models.ImageField(blank=True, upload_to='contest_images/', verbose_name='상세 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '공모전',
                'verbose_name_plural': '공모전 목록',
                'ordering': ['end_date'],
            },
        ),
    ]
